name: Descarga precio de hoy

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run download-today-status
    - run: |
        git config user.name soker90
        git config user.email eduparra90@gmail.com
        git add .
        git commit -m "Add report for today"
        git push