name: interactBot

on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *

env:
  GASOLINA_CHAT_ID: ${{ secrets.GASOLINA_CHAT_ID }}
  DIESEL_CHAT_ID: ${{ secrets.DIESEL_CHAT_ID }}
  TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
  FUEL_STATION_ID: 7882

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js version 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run interact
